using System;

namespace CardGameExample
{
	// Perhaps this file can be auto-generated by T4 script
	public static class Assets
	{
		public static class Materials
		{
			public const string Particle = "Materials/Particle.xml";
			public const string Skybox = "Materials/Skybox.xml";
			public const string Smoke = "Materials/Smoke.xml";
			public const string Stone = "Materials/Stone.xml";
			public const string Water = "Materials/Water.xml";
		}

		public static class Models
		{
			public const string Box = "Models/Box.mdl";
			public const string Cone = "Models/Cone.mdl";
			public const string Cylinder = "Models/Cylinder.mdl";
			public const string Dome = "Models/Dome.mdl";
			public const string Pyramid = "Models/Pyramid.mdl";
			public const string Sphere = "Models/Sphere.mdl";
			public const string Torus = "Models/Torus.mdl";
			public const string Plane = "Models/Plane.mdl";
		}

		public static class Particles
		{
			public const string Burst = "Particle/Burst.pex";
			public const string Dust = "Particle/Dust.pex";
			public const string Fire = "Particle/Fire.pex";
			public const string Smoke = "Particle/Smoke.pex";
		}

		public static class Sounds
		{

		}

		public static class Fonts
		{
			public const string AnonymousPro = "Fonts/Anonymous Pro.ttf";
			public const string BlueHighway = "Fonts/BlueHighway.ttf";
		}

		public static class PostProcess
		{
			public const string FXAA3 = "PostProcess/FXAA3.xml";
			public const string GreyScale = "PostProcess/GreyScale.xml";
			public const string Bloom = "PostProcess/Bloom.xml";
			public const string Blur = "PostProcess/Blur.xml";
		}

		public static class Textures
		{
			public const string mmGameLogo = "Textures/mmGameLogo.png";
		}
	}
}
